name: Deploy React App
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: [18.x, 20.x, 22.x]
 
    - name: Install dependencies
      run: npm ci
 
    - name: Build
      run: npm run build
 
    - name: Deploy to GitHub Pages
      run: npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
